import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# Do not print debug messages in production
config :logger, level: :info

config :binckquotes, BinckquotesWeb.Endpoint,
  cache_static_manfest: "priv/static/cache_manifest.json",
  check_origin: true,
  check_origin: [ "https://binckquotes.gigalixirapp.com/",
                  "https://binckquotes.gigalixirapp.com/nieuw",
                  "https://binckquotes.gigalixirapp.com/oud",
                  "https://binckquotes.gigalixirapp.com/random",
                  "https://binckquotes.gigalixirapp.com/management",
                  "https://binckquotes.gigalixirapp.com/api/getquotes" ]
      url: [host: "https://binckquotes.gigalixirapp.com", port: 4000],
      https: [
        cipher_suite: :strong,
        keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
        certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
      ]
